print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/armin/GitHub/lensflare-unityUI/UI/Assets/Misc/Taurus.mb"`)
{		
	file -o "/Users/armin/GitHub/lensflare-unityUI/UI/Assets/Misc/Taurus.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/armin/GitHub/lensflare-unityUI/UI/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/armin/GitHub/lensflare-unityUI/UI/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/armin/GitHub/lensflare-unityUI/UI/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
